### ISSUE TITLE
Support classical arguments and return types for defcals

### ISSUE THREAD

**Issue by PhilReinhold** [openqasm/oqpy#7]

**Comment by Swordcat** [comment]
I want to contribute to this issue.

Should I go and submit a PR or should we discuss how this could be implemented? e.g. the function signature of the defcal context manager.

**Comment by PhilReinhold** [comment]
Hi @Swordcat and thanks for the interest in this issue! We are in the process of reviewing a proposed implementation in #20. Feel free to leave feedback on this proposal.
